-- FarmaSystemDB — Referencia de scripts SQL
--
-- ORDEN DE EJECUCIÓN EN SQL SERVER:
--   1. database/schema/FarmaSystemDB.sql   → tablas, FKs, constraints
--   2. Scripts/StoredProcedures.sql        → stored procedures (idempotente)
--   3. Scripts/AuthUsuarios.sql            → usuarios de prueba (opcional)
--
-- Los SP usados por la API están definidos en StoredProcedures.sql:
--   sp_RegistrarVenta, sp_AgregarDetalleVenta, sp_RegistrarDetalleVenta,
--   sp_RegistrarCompra, sp_RegistrarDetalleCompra, sp_ConsultarInventario,
--   sp_ReporteVentasPorPeriodo, sp_BuscarMedicamentos, sp_BuscarClientes,
--   sp_ObtenerDashboard
--
-- Ejecutar SPs con:
--   sqlcmd -S localhost -d FarmaSystemDB -E -i StoredProcedures.sql
